/** SSOT for booth strings — MC_PS narrative on glass */
export const COPY = {
  nav: { identify: "Identify", generate: "Generate", defend: "Defend" },
  chip: {
    live: "LIVE · search + LLM",
    recorded: "RECORDED",
    frozen: "FROZEN · locked holdout",
    rules: "RULES · policy table",
  },
  stages: {
    landscape: "Landscape",
    discover: "Discover",
    review: "Review",
    detection: "Detection",
    interventions: "Interventions",
    feedback: "Improve defense",
    hyperparameters: "Optuna — hyperparameter tuning",
  },
  identify: {
    landscapeCaption: "Emerging GenAI payment fraud — breadth and depth.",
    discoverCaption: "Allowlisted OSINT — not a live issuer feed.",
    reviewCaption: "Add attacks we can simulate with fidelity.",
    discover: "Discover emerging threats",
    rest: "Catalog of 24 techniques across five categories. Discover proposes new attacks from allowlisted OSINT.",
    firstStillCaption: "Allowlisted OSINT + seed catalog — not an issuer feed",
    categories: "5 categories",
    scanning: "Collecting from allowlisted OSINT",
    review: "Proposed attacks",
    add: "Add to catalog",
    dismiss: "Dismiss",
    unsafe: "Not safe",
    continue: "Continue to Generate",
    continueSeed: "Continue with catalog seed",
    continueDisabled: "Add at least one attack to the catalog, or continue on catalog seed.",
    fallback: "Using recorded FinCEN / RBI corpus.",
    gapCta: "Discover this coverage gap",
    attackId: "Attack ID",
    coverageGap: "Coverage gap",
    emptyProposed: "No new typologies this run.",
    inCatalog: "In catalog",
    catalogContext: "Earlier discoveries approved in this lab.",
    catalogFail: "Could not load catalog. Retry.",
    sseDrop: "Discovery interrupted. Retry, or load a recorded pack (⌘K).",
    narrowScan: "Narrow the scan",
    census: (n: number) => String(n),
  },
  generate: {
    caption: "Simulate attacks at payment fidelity.",
    primary: "Simulate payment traffic",
    empty: "No corpus on this session. Simulate payment traffic · seed required for audit.",
    catalogSeed: "Catalog seed · RECORDED",
    continue: "Continue to Defend",
    continueDisabled: "Fidelity not yet known for this corpus.",
    fidelityPass:
      "Fidelity pass — PSI versus this run's priors within band · fraud-rate in lab envelope · not a live UPI distribution.",
    fidelityFail: "Fidelity advisory — review PSI and fraud-rate before production.",
    fidelityChecking: "Checking fidelity — PSI, fraud-rate band, mule fan-in.",
    canary: "Canary — pinned FinCEN typology",
    fullPopulation: "Full population (proof)",
    seedStamp: "seed",
    running: (done: number, total: number, seed: number) => `${done} of ${total} events · seed ${seed}`,
  },
  defend: {
    detectionCaption: "Holdout recall at a genuine false-alarm cap.",
    interventionsCaption: "Detect, flag, and mitigate — what the bank would do.",
    feedbackCaption: "Feedback loop — retrain on the fraud type we missed.",
    feedbackBody:
      "Simulated misses become extra training. A new holdout world grades the result — the loop cannot mark its own homework.",
    hyperparametersCaption: "Search better settings on validation. Holdout stays frozen.",
    empty: "No score on glass. Continue from Generate, or load a recorded pack (⌘K).",
    scoring: "Scoring this run",
    op: (r: string, f: string) => `Operating point — recall ${r}% @ genuine FPR ${f}%`,
    frozen: "Locked holdout. Threshold chosen on the training validation fold; scored once.",
    feedbackLoop: "Run feedback loop",
    feedbackRunning: "Running feedback loop",
    continueOptuna: "Continue to Optuna",
    runOptuna: "Run Optuna — hyperparameter tuning",
    optunaRunning: "Searching settings on validation",
    optunaSkipped: "Not enough fraud examples — kept default settings.",
    jumpOptuna: "Jump ahead to Optuna",
    backIdentify: "Back to Identify",
    recompute: "Recompute on this run",
    retrainDisabled: "Needs this session's generate run.",
    feedbackFail: "Could not run feedback loop. Retry.",
    tuneFail: "Could not run Optuna. Retry.",
    compareBase: "Base",
    compareFeedback: "After feedback loop",
    compareOptuna: "After Optuna",
    continueInterventions: "Continue to Interventions",
    continueFeedback: "Continue to Improve defense",
    interventions: "Interventions",
    holdoutCaveat:
      "Threshold chosen on the training validation fold. Holdout scored once. Thresholds are not searched on the test labels.",
    chartTitle: "Recall under a genuine false-positive cap",
    chartSubtitle: "Solid is after the feedback loop.",
    scoreFail: "Could not score this run. Retry, or load locked holdout (⌘K).",
    seriesDetector: "Before feedback",
    seriesAfterRetrain: "After feedback loop",
  },
  skip: "Skip to result",
  palette: {
    boothDemo: "Run booth demo",
    recordedIdentify: "Play recorded Identify",
    lockedHoldout: "Load locked holdout",
    recordedRetrain: "Play recorded retrain",
    returnLive: "Return to live search",
    copySeed: "Copy seed",
    copyOp: "Copy operating point",
    fitHyperparams: "Fit hyperparameters (proof)",
  },
  policy: {
    allow: "Allow",
    notify: "Notify",
    stepUp: "Step-up",
    hold: "Hold",
    decline: "Decline",
    restrictPayeeCredit: "Restrict (payee credit)",
  },
  coverage: {
    liveRule: "Live rule",
    draftRule: "Draft rule",
    coverageGap: "Coverage gap",
  },
  logPill: (n: number) => `↓ Live · ${n} new`,
  wordmark: "AegisLoop",
} as const;
