/** SSOT for booth strings — IMPLEMENTATION-SPEC §6.8 */
export const COPY = {
  nav: { identify: "Identify", generate: "Generate", defend: "Defend" },
  chip: {
    live: "LIVE · search + LLM",
    recorded: "RECORDED",
    frozen: "FROZEN · locked holdout",
    rules: "RULES · policy table",
  },
  identify: {
    discover: "Discover emerging threats",
    rest: "Catalog of 24 techniques across five categories. Discover proposes new attacks from allowlisted OSINT.",
    firstStillCaption: "Allowlisted OSINT + seed catalog — not an issuer feed",
    categories: "5 categories",
    scanning: "Collecting from allowlisted OSINT",
    review: "Proposed attacks",
    add: "Add to catalog",
    dismiss: "Dismiss",
    unsafe: "Mark unsafe",
    continue: "Continue to Generate",
    continueSeed: "Continue with catalog seed",
    continueDisabled: "Add at least one attack to the catalog, or continue on catalog seed.",
    fallback: "Using recorded FinCEN / RBI corpus.",
    gapCta: "Discover this coverage gap",
    attackId: "Attack ID",
    coverageGap: "Coverage gap",
    emptyProposed: "No proposed attacks yet. Discover emerging threats, or continue on catalog seed.",
    inCatalog: "In catalog",
    catalogContext: "Earlier discoveries approved in this lab.",
    catalogFail: "Could not load catalog. Retry.",
    sseDrop: "Discovery interrupted. Use a recorded pack (⌘K).",
    narrowScan: "Narrow the scan",
  },
  generate: {
    primary: "Simulate payment traffic",
    empty: "No corpus on this session. Simulate payment traffic (demo scale) · seed required for audit.",
    catalogSeed: "Catalog seed · RECORDED",
    continue: "Continue to Defend",
    continueDisabled: "Fidelity not yet known for this corpus.",
    fidelityPass:
      "Fidelity pass — PSI versus this run’s priors within band · fraud-rate in lab envelope · not a live UPI distribution.",
    fidelityFail: "Fidelity fail — do not score this run.",
    fidelityChecking: "Checking fidelity — PSI, fraud-rate band, mule fan-in.",
    canary: "Canary — pinned FinCEN typology",
    fullPopulation: "Full population (proof)",
    seedStamp: "seed",
  },
  defend: {
    empty: "No score on glass. Continue from Generate, or load a recorded pack (⌘K).",
    scoring: "Scoring this run",
    op: (r: string, f: string) => `Operating point — recall ${r}% @ genuine FPR ${f}%`,
    frozen: "Locked holdout. Threshold chosen on the training validation fold; scored once.",
    retrain: "Retrain from missed fraud",
    retrainDisabled: "Needs this session’s generate run. Locked holdout is the booth still.",
    retrainFail: "Could not retrain. Showing locked holdout overlay.",
    retrainProof: "Proof — not the booth click.",
    confirmRetrain:
      "Retrain from missed fraud on this run’s scale. Promote only if family ranking and genuine FPR do not collapse.",
    recompute: "Recompute on this run",
    updated: "Defense updated — second series is after retrain from missed fraud.",
    seriesDetector: "Detector",
    seriesAfterRetrain: "After retrain",
    interventions: "Interventions",
    holdoutCaveat:
      "Threshold chosen on the training validation fold. Holdout scored once. Thresholds are not searched on the test labels.",
    chartTitle: "Recall under a genuine false-positive cap",
    chartSubtitle: "Internal holdout world · not production · not external transfer",
    scoreFail: "Could not score this run. Load locked holdout (⌘K).",
  },
  skip: "Skip to result",
  palette: {
    recordedIdentify: "Play recorded Identify",
    lockedHoldout: "Load locked holdout",
    recordedRetrain: "Play recorded retrain",
    returnLive: "Return to live search",
    copySeed: "Copy seed",
    copyOp: "Copy operating point",
    fitHyperparams: "Fit hyperparameters (proof)",
  },
  policy: {
    allow: "Allow",
    notify: "Notify",
    stepUp: "Step-up",
    hold: "Hold",
    decline: "Decline",
    restrictPayeeCredit: "Restrict (payee credit)",
  },
  coverage: {
    liveRule: "Live rule",
    draftRule: "Draft rule",
    coverageGap: "Coverage gap",
  },
  logPill: (n: number) => `↓ Live · ${n} new`,
  wordmark: "AegisLoop",
} as const;
